/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:f79b8178-b42b-4de9-9902-c24f9673fa33",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_qx8AEKWX8",
    "aws_user_pools_web_client_id": "torv25stn8ekbn2mku6pc187a",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ps2y4l6fknehdaq7pi7zfwmmlm.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-di4zainffnfjddtl2quqoiafmi",
    "aws_user_files_s3_bucket": "bukee112110-dev",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
